export enum Routes {
    DRAWER = 'Drawer',
    STACK = 'Stack',
    TABS = 'Tabs',
    HISTORY = 'History',
    ABOUT = 'About',
    MAP = 'Map',
    ROUTE_MAP = 'Route Map',
    POIS = 'Pois',
    POI_DETAILS = 'Poi Details',
    ROUTES = 'Routes',
    ROUTE_DETAILS = 'Route Details',
    FAVORITES = 'Favorites',
    FILTER = 'Filter',
};
